dist: xenial
language: python
python: 3.7
# We lint with pylint before linting with shellcheck because the former step is
# far faster than the latter step. The virtualenv is deactivated during all
# shellcheck linting to avoid any possible environment-related errors.
before_install:
    - pip install pylint
    - sudo apt-get install -y shellcheck
jobs:
  include:
    - stage: lint
      name: "Lint the code"
      script: make lint
    - stage: build
      name: "Build pulp-fixtures docker image"
      before_install: skip
      script:
        - docker build -f Containerfile -t pulp/pulp-fixtures .
        - docker run -d -e BASE_URL=http://example.com -p 8000:80 pulp/pulp-fixtures
        - sleep 2 # it can take a couple seconds for sed to run and nginx to boot
        - curl --fail localhost:8000/file/PULP_MANIFEST
        - curl --fail localhost:8000/debian/dists/ragnarok/Release
        - '[[ $(curl localhost:8000/rpm-mirrorlist-good) == "http://example.com/rpm-unsigned/" ]] || exit 1'
      deploy:
        - provider: script
          script: bash .travis/docker-push.sh
          on:
            branch: master
        - provider: script
          script: bash .travis/quay-push.sh
          on:
            branch: master
