dist: xenial
language: python
python: 3.7
# We lint with pylint before linting with shellcheck because the former step is
# far faster than the latter step. The virtualenv is deactivated during all
# shellcheck linting to avoid any possible environment-related errors.
before_install:
    - pip install pylint
    - sudo apt-get install -y shellcheck libpod
jobs:
  include:
    - stage: lint
      name: "Lint the code"
      script: make lint
    - stage: build
      name: "Build pulp-fixtures docker image"
      before_install: skip
      script:
        - buildah bud -f Containerfile -t pulp/pulp-fixtures .
        - podman run -d -p 8000:80 pulp/pulp-fixtures
        - curl --fail localhost:8000/fixtures/file/PULP_MANIFEST
        - curl --fail localhost:8000/fixtures/debian/dists/ragnarok/Release
      deploy:
        - provider: script
          script: bash .travis/docker-push.sh
          on:
            branch: master
        - provider: script
          script: bash .travis/quay-push.sh
          on:
            branch: master
