dist: xenial
language: python
python: 3.7
# We lint with pylint before linting with shellcheck because the former step is
# far faster than the latter step. The virtualenv is deactivated during all
# shellcheck linting to avoid any possible environment-related errors.
before_install:
    - pip install pylint
    - sudo apt-get install -y shellcheck
jobs:
  include:
    - stage: lint
      name: "Lint the code"
      script: make lint
    - stage: build
      name: "Build pulp-fixtures docker image"
      before_install: skip
      script:
        - docker build -t quay.io/pulp/pulp-fixtures .
        - docker run -d -p 8000:80 quay.io/pulp/pulp-fixtures
        - curl --fail localhost:8000/fixtures/file/PULP_MANIFEST
      deploy:
        provider: script
        script: bash .travis/quay-push.sh
        on:
          branch: master
